// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRUjXt_dOoE897VkBYUArwkTOzOKvcSs',
    appId: '1:780083421710:web:c33319a8d05a229034d25f',
    messagingSenderId: '780083421710',
    projectId: 'newproject-a6786',
    authDomain: 'newproject-a6786.firebaseapp.com',
    storageBucket: 'newproject-a6786.appspot.com',
    measurementId: 'G-16BWS9MLD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzieXGMPpMDRxigOD9Rcetj0NUmyDghuQ',
    appId: '1:780083421710:android:9eb26c8c8cc3231f34d25f',
    messagingSenderId: '780083421710',
    projectId: 'newproject-a6786',
    storageBucket: 'newproject-a6786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBj3t9iVtIkMSWw1CzMuDZsktPPojurc',
    appId: '1:780083421710:ios:cba90a81aabcc76634d25f',
    messagingSenderId: '780083421710',
    projectId: 'newproject-a6786',
    storageBucket: 'newproject-a6786.appspot.com',
    androidClientId: '780083421710-oc6c8edc9g7sech2avv3ehgva5sb0lo5.apps.googleusercontent.com',
    iosClientId: '780083421710-fj8d0l55v98u9cr2vo0tt6roqohe1fqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.khadaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHBj3t9iVtIkMSWw1CzMuDZsktPPojurc',
    appId: '1:780083421710:ios:c3eae3e6ac6a62da34d25f',
    messagingSenderId: '780083421710',
    projectId: 'newproject-a6786',
    storageBucket: 'newproject-a6786.appspot.com',
    androidClientId: '780083421710-oc6c8edc9g7sech2avv3ehgva5sb0lo5.apps.googleusercontent.com',
    iosClientId: '780083421710-ji3538619l4c8erfbepim7facr0hdolb.apps.googleusercontent.com',
    iosBundleId: 'com.example.khadaBook.RunnerTests',
  );
}
